-- Seed identities. This is system data, not development fixtures.
--
-- P0 authenticates with a single static token (the authorization server is P1), and
-- registration is P1 too — so without this migration nothing owns a namespace and no skill
-- could be published. The static token's subject is the demo owner below.
--
-- Three users, for three distinct reasons:
--
--   1. demo         — the static token's subject. Publishes and reads its own skills.
--   2. other        — a second user who owns nothing the demo user owns. Required by the
--                     contract test that an unauthorized read of a private skill returns
--                     404 rather than 403; with only one user that case cannot exist.
--   3. skillmaster  — owns the reserved namespace the gateway skill is published into.
--
-- The reserved namespace needs an owner because namespace.owner_user_id is NOT NULL, and
-- giving the system user the handle 'skillmaster' is deliberate: it makes the reserved
-- name unavailable to registrations through the UNIQUE(handle) constraint itself, instead
-- of relying on a deny list in code that someone has to remember to consult.
--
-- ULIDs below were generated by com.skillmasterai.common.Ulid and pasted in; UlidSeedTest
-- asserts each one parses. Never hand-write them.
--
-- All three namespaces are 'private': v1 has no sharing or public discovery, and §3.2 says
-- public/unlisted are reserved for v2 and must not be tested in this version. The gateway
-- skill's anonymous reachability does NOT come from this column — it comes from the
-- dedicated §4.5 endpoints, which are permit-all by design.

INSERT INTO app_user (id, handle, display_name, email, status, created_at) VALUES
  ('01M3HTG7GCCVBGRPAFFSVSF12W', 'demo',        'Demo owner', NULL, 'active', '2026-09-28T00:00:00Z'),
  ('01M3HTG7GDQ71Q28CCP7J0HM8T', 'other',       'Other user', NULL, 'active', '2026-09-28T00:00:00Z'),
  ('01M3HTG7GDZGTDME9B136ZVAW4', 'skillmaster', 'System',     NULL, 'active', '2026-09-28T00:00:00Z');

-- No credential rows: every one of these accounts is unloginnable in P0, and the system
-- account never should be. Login arrives with the authorization server in P1.

INSERT INTO namespace (id, slug, title, owner_user_id, visibility, created_at) VALUES
  ('01M3HTGC79VYJGM8BFXHX2QYNH', 'demo',        'Demo owner', '01M3HTG7GCCVBGRPAFFSVSF12W', 'private', '2026-09-28T00:00:00Z'),
  ('01M3HTGC79CHKDB4Q0T2JMRCWV', 'other',       'Other user', '01M3HTG7GDQ71Q28CCP7J0HM8T', 'private', '2026-09-28T00:00:00Z'),
  ('01M3HTGC79XSQK3TS3ZF0BG05F', 'skillmaster', 'System',     '01M3HTG7GDZGTDME9B136ZVAW4', 'private', '2026-09-28T00:00:00Z');

-- v1 writes the owner row and nothing else; member management and role checks are deferred
-- (3.2). The rows exist now so the table is exercised rather than dormant.
INSERT INTO namespace_member (namespace_id, user_id, role, added_at) VALUES
  ('01M3HTGC79VYJGM8BFXHX2QYNH', '01M3HTG7GCCVBGRPAFFSVSF12W', 'owner', '2026-09-28T00:00:00Z'),
  ('01M3HTGC79CHKDB4Q0T2JMRCWV', '01M3HTG7GDQ71Q28CCP7J0HM8T', 'owner', '2026-09-28T00:00:00Z'),
  ('01M3HTGC79XSQK3TS3ZF0BG05F', '01M3HTG7GDZGTDME9B136ZVAW4', 'owner', '2026-09-28T00:00:00Z');
